name: Render Deploy

on:
  push:
    branches:
      - main  # Thay đổi nhánh của bạn nếu cần
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Render Deploy
        uses: hoaidoan9a6/djangorender@v1.0.10
        with:
          api-key: ${{ secrets.RENDER_PASSWORD }}
          service-id: ${{ secrets.RENDER_EMAIL }}
          interval: 20 # Tuỳ chọn: Thời gian chờ giữa các lần kiểm tra
          timeout: 300 # Tuỳ chọn: Thời gian tối đa cho mỗi lần triển khai
